// Generated by CoffeeScript 1.3.3

/*
global helper for chai.should()
*/


(function() {

  GLOBAL.should = require('chai').should();

  /*
  addon for lib_path
  */


  GLOBAL.lib_path = '../src/';

}).call(this);
